rm Arbeit.aux
rm Arbeit.bbl
rm Arbeit.bcf
rm Arbeit.blg
rm Arbeit.dvi
rm Arbeit.fdb_latexmk
rm Arbeit.fls
rm Arbeit.lof
rm Arbeit.log
rm Arbeit.lol
rm Arbeit.lot
rm Arbeit.out
rm Arbeit.pdf
rm Arbeit.toc
rm Arbeit.run.xml
rm Arbeit.synctex.gz
rm Arbeit.tex.bbl
rm Arbeit.tex.blg
